#Install macro for fblib libraries
MACRO (FBLIB_INSTALL_LIB NAME)
IF (NOT WIN32)
  INSTALL(TARGETS ${NAME} ${NAME} ${NAME}
    LIBRARY DESTINATION ${FBLIB_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    ARCHIVE DESTINATION ${FBLIB_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    RUNTIME DESTINATION ${FBLIB_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
  )
ELSE (NOT WIN32)
  INSTALL(TARGETS ${NAME} ${NAME} ${NAME}
    LIBRARY DESTINATION ${FBLIB_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    ARCHIVE DESTINATION ${FBLIB_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    RUNTIME DESTINATION ${FBLIB_EXECUTABLE_OUTPUT_DIR}
    COMPONENT applications
  )
ENDIF (NOT WIN32)
ENDMACRO (FBLIB_INSTALL_LIB)

# Install all fblib and third parties headers
MACRO (FBLIB_INSTALL_ALL_HEADERS)
  INSTALL(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
          DESTINATION ${FBLIB_HEADERS_OUTPUT_DIR}
          COMPONENT headers
          FILES_MATCHING PATTERN "*"
                         PATTERN ".svn" EXCLUDE
                         PATTERN "*.cpp" EXCLUDE
                         PATTERN "*.cc" EXCLUDE
                         PATTERN "*.c" EXCLUDE
                         PATTERN "*~" EXCLUDE
                         PATTERN "CMakeLists.txt" EXCLUDE
        )
ENDMACRO (FBLIB_INSTALL_ALL_HEADERS)

# Install macro for fblib binaries
MACRO (FBLIB_INSTALL_EXE NAME)
  # install libraries
  INSTALL(TARGETS ${NAME}
    RUNTIME DESTINATION ${FBLIB_EXECUTABLE_OUTPUT_DIR}
    COMPONENT applications
  )
ENDMACRO (FBLIB_INSTALL_EXE)

#Install macro for third parties libraries
MACRO (FBLIB_INSTALL_THIRD_PARTY_LIB NAME)
IF (NOT WIN32)
  INSTALL(TARGETS ${NAME} ${NAME} ${NAME}
    LIBRARY DESTINATION ${FBLIB_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    ARCHIVE DESTINATION ${FBLIB_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    RUNTIME DESTINATION ${FBLIB_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
  )
ELSE (NOT WIN32)
  INSTALL(TARGETS ${NAME} ${NAME} ${NAME}
    LIBRARY DESTINATION ${FBLIB_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    ARCHIVE DESTINATION ${FBLIB_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    RUNTIME DESTINATION ${FBLIB_EXECUTABLE_OUTPUT_DIR}
    COMPONENT applications
  )
ENDIF (NOT WIN32)
ENDMACRO (FBLIB_INSTALL_THIRD_PARTY_LIB)


