#Install macro for mvg libraries
MACRO (MVG_INSTALL_LIB NAME)
IF (NOT WIN32)
  INSTALL(TARGETS ${NAME} ${NAME} ${NAME}
    LIBRARY DESTINATION ${MVG_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    ARCHIVE DESTINATION ${MVG_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    RUNTIME DESTINATION ${MVG_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
  )
ELSE (NOT WIN32)
  INSTALL(TARGETS ${NAME} ${NAME} ${NAME}
    LIBRARY DESTINATION ${MVG_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    ARCHIVE DESTINATION ${MVG_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    RUNTIME DESTINATION ${MVG_EXECUTABLE_OUTPUT_DIR}
    COMPONENT applications
  )
ENDIF (NOT WIN32)
ENDMACRO (MVG_INSTALL_LIB)

# Install all mvg and third parties headers
MACRO (MVG_INSTALL_ALL_HEADERS)
  INSTALL(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
          DESTINATION ${MVG_HEADERS_OUTPUT_DIR}
          COMPONENT headers
          FILES_MATCHING PATTERN "*"
                         PATTERN ".svn" EXCLUDE
                         PATTERN "*.cpp" EXCLUDE
                         PATTERN "*.cc" EXCLUDE
                         PATTERN "*.c" EXCLUDE
                         PATTERN "*~" EXCLUDE
                         PATTERN "CMakeLists.txt" EXCLUDE
        )
ENDMACRO (MVG_INSTALL_ALL_HEADERS)

# Install macro for mvg binaries
MACRO (MVG_INSTALL_EXE NAME)
  # install libraries
  INSTALL(TARGETS ${NAME}
    RUNTIME DESTINATION ${MVG_EXECUTABLE_OUTPUT_DIR}
    COMPONENT applications
  )
ENDMACRO (MVG_INSTALL_EXE)

#Install macro for third parties libraries
MACRO (MVG_INSTALL_THIRD_PARTY_LIB NAME)
IF (NOT WIN32)
  INSTALL(TARGETS ${NAME} ${NAME} ${NAME}
    LIBRARY DESTINATION ${MVG_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    ARCHIVE DESTINATION ${MVG_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    RUNTIME DESTINATION ${MVG_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
  )
ELSE (NOT WIN32)
  INSTALL(TARGETS ${NAME} ${NAME} ${NAME}
    LIBRARY DESTINATION ${MVG_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    ARCHIVE DESTINATION ${MVG_LIBRARY_OUTPUT_DIR}
    COMPONENT libraries
    RUNTIME DESTINATION ${MVG_EXECUTABLE_OUTPUT_DIR}
    COMPONENT applications
  )
ENDIF (NOT WIN32)
ENDMACRO (MVG_INSTALL_THIRD_PARTY_LIB)


