# ----------------------------------------------------------------------------
# Transform the variables MVG_XXX="ON/OFF" to CMAKE_MVG_XXX="1/0"
# ----------------------------------------------------------------------------
MACRO(CREATE_CMAKE_MVG_DEFINE defName)
	IF(${defName} MATCHES "ON")
		SET(CMAKE_${defName} "1")
	ELSE(${defName} MATCHES "ON")
		SET(CMAKE_${defName} "0")
	ENDIF(${defName} MATCHES "ON")
ENDMACRO(CREATE_CMAKE_MVG_DEFINE)

CREATE_CMAKE_MVG_DEFINE(MVG_ALWAYS_CHECKS_DEBUG)
CREATE_CMAKE_MVG_DEFINE(MVG_ALWAYS_CHECKS_DEBUG_MATRICES)
CREATE_CMAKE_MVG_DEFINE(MVG_HAS_BUMBLEBEE)
CREATE_CMAKE_MVG_DEFINE(MVG_HAS_SVS)
CREATE_CMAKE_MVG_DEFINE(MVG_HAS_ASSERT)
CREATE_CMAKE_MVG_DEFINE(MVG_HAS_STACKED_EXCEPTIONS)
CREATE_CMAKE_MVG_DEFINE(MVG_ENABLE_EMBEDDED_GLOBAL_PROFILER)
CREATE_CMAKE_MVG_DEFINE(MVG_HAS_ASIAN_FONTS)
CREATE_CMAKE_MVG_DEFINE(CMAKE_MVG_HAS_INOTIFY)
